/*
 * Onionoo
 * Onionoo
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package me.learmonth.iain.onionoo;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * BridgeSummaryObject
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-17T21:49:33.054+01:00")
public class BridgeSummaryObject {
  @SerializedName("n")
  private String n = null;

  @SerializedName("h")
  private String h = null;

  @SerializedName("a")
  private List<String> a = null;

  @SerializedName("r")
  private Boolean r = null;

  public BridgeSummaryObject n(String n) {
    this.n = n;
    return this;
  }

   /**
   * Get n
   * @return n
  **/
  @ApiModelProperty(value = "")
  public String getN() {
    return n;
  }

  public void setN(String n) {
    this.n = n;
  }

  public BridgeSummaryObject h(String h) {
    this.h = h;
    return this;
  }

   /**
   * Get h
   * @return h
  **/
  @ApiModelProperty(required = true, value = "")
  public String getH() {
    return h;
  }

  public void setH(String h) {
    this.h = h;
  }

  public BridgeSummaryObject a(List<String> a) {
    this.a = a;
    return this;
  }

  public BridgeSummaryObject addAItem(String aItem) {
    if (this.a == null) {
      this.a = new ArrayList<String>();
    }
    this.a.add(aItem);
    return this;
  }

   /**
   * Get a
   * @return a
  **/
  @ApiModelProperty(value = "")
  public List<String> getA() {
    return a;
  }

  public void setA(List<String> a) {
    this.a = a;
  }

  public BridgeSummaryObject r(Boolean r) {
    this.r = r;
    return this;
  }

   /**
   * Get r
   * @return r
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getR() {
    return r;
  }

  public void setR(Boolean r) {
    this.r = r;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BridgeSummaryObject bridgeSummaryObject = (BridgeSummaryObject) o;
    return Objects.equals(this.n, bridgeSummaryObject.n) &&
        Objects.equals(this.h, bridgeSummaryObject.h) &&
        Objects.equals(this.a, bridgeSummaryObject.a) &&
        Objects.equals(this.r, bridgeSummaryObject.r);
  }

  @Override
  public int hashCode() {
    return Objects.hash(n, h, a, r);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BridgeSummaryObject {\n");
    
    sb.append("    n: ").append(toIndentedString(n)).append("\n");
    sb.append("    h: ").append(toIndentedString(h)).append("\n");
    sb.append("    a: ").append(toIndentedString(a)).append("\n");
    sb.append("    r: ").append(toIndentedString(r)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

