/*
 * Onionoo
 * Onionoo
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package me.learmonth.iain.onionoo;

import me.learmonth.iain.onionoo.ApiCallback;
import me.learmonth.iain.onionoo.ApiClient;
import me.learmonth.iain.onionoo.ApiException;
import me.learmonth.iain.onionoo.ApiResponse;
import me.learmonth.iain.onionoo.Configuration;
import me.learmonth.iain.onionoo.Pair;
import me.learmonth.iain.onionoo.ProgressRequestBody;
import me.learmonth.iain.onionoo.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.math.BigDecimal;
import me.learmonth.iain.onionoo.SummaryDocument;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DocumentsApi {
    private ApiClient apiClient;

    public DocumentsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DocumentsApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for getSummary
     * @param type Return only relay (parameter value relay) or only bridge documents (parameter value bridge). Parameter values are case-insensitive. (optional)
     * @param running Return only running (parameter value true) or only non-running relays and/or bridges (parameter value false). Parameter values are case-insensitive. (optional)
     * @param search Return only (1) relays with the parameter value matching (part of a) nickname, (possibly $-prefixed) beginning of a hex-encoded fingerprint, any 4 hex character block of a space-separated fingerprint, beginning of a base64-encoded fingerprint without trailing equal signs, or beginning of an IP address (possibly enclosed in square brackets in case of IPv6), (2) bridges with (part of a) nickname or (possibly $-prefixed) beginning of a hashed hex-encoded fingerprint, and (3) relays and/or bridges matching a given qualified search term. Searches by relay IP address include all known addresses used for onion routing and for exiting to the Internet. Searches for beginnings of IP addresses are performed on textual representations of canonical IP address forms, so that searches using CIDR notation or non-canonical forms will return empty results. Searches are case-insensitive, except for base64-encoded fingerprints. If multiple search terms are given, separated by spaces, the intersection of all relays and bridges matching all search terms will be returned. Complete hex-encoded fingerprints should always be hashed using SHA-1, regardless of searching for a relay or a bridge, in order to not accidentally leak non-hashed bridge fingerprints in the URL. Qualified search terms have the form \&quot;key:value\&quot; (without double quotes) with \&quot;key\&quot; being one of the parameters listed here except for \&quot;search\&quot;, \&quot;fingerprint\&quot;, \&quot;order\&quot;, \&quot;limit\&quot;, \&quot;offset\&quot;, and \&quot;fields\&quot;, and \&quot;value\&quot; being the string that will internally be passed to that parameter. If a qualified search term for a given \&quot;key\&quot; is specified more than once, only the first \&quot;value\&quot; is considered. (optional)
     * @param lookup Return only the relay with the parameter value matching the fingerprint or the bridge with the parameter value matching the hashed fingerprint. Fingerprints should always be hashed using SHA-1, regardless of looking up a relay or a bridge, in order to not accidentally leak non-hashed bridge fingerprints in the URL. Lookups only work for full fingerprints or hashed fingerprints consisting of 40 hex characters. Lookups are case-insensitive. (optional)
     * @param fingerprint Return only the relay with the parameter value matching the fingerprint or the bridge with the parameter value matching the hashed fingerprint. Fingerprints must consist of 40 hex characters, case does not matter. This parameter is quite similar to the lookup parameter with two exceptions: (1) the provided relay fingerprint or hashed bridge fingerprint must not be hashed (again) using SHA-1; (2) the response will contain any matching relay or bridge regardless of whether they have been running in the past week. (optional)
     * @param country Return only relays which are located in the given country as identified by a two-letter country code. Filtering by country code is case-insensitive. (optional)
     * @param as Return only relays which are located in the given autonomous system (AS) as identified by the AS number (with or without preceding \&quot;AS\&quot; part). Filtering by AS number is case-insensitive. (optional)
     * @param flag Return only relays which have the given relay flag assigned by the directory authorities. Note that if the flag parameter is specified more than once, only the first parameter value will be considered. Filtering by flag is case-insensitive. (optional)
     * @param firstSeenDays Return only relays or bridges which have first been seen during the given range of days ago. A parameter value \&quot;x-y\&quot; with x &lt;&#x3D; y returns relays or bridges that have first been seen at least x and at most y days ago. Accepted short forms are \&quot;x\&quot;, \&quot;x-\&quot;, and \&quot;-y\&quot; which are interpreted as \&quot;x-x\&quot;, \&quot;x-infinity\&quot;, and \&quot;0-y\&quot;. (optional)
     * @param lastSeenDays Return only relays or bridges which have last been seen during the given range of days ago. A parameter value \&quot;x-y\&quot; with x &lt;&#x3D; y returns relays or bridges that have last been seen at least x and at most y days ago. Accepted short forms are \&quot;x\&quot;, \&quot;x-\&quot;, and \&quot;-y\&quot; which are interpreted as \&quot;x-x\&quot;, \&quot;x-infinity\&quot;, and \&quot;0-y\&quot;. Note that relays and bridges that haven&#39;t been running in the past week are not included in results, so that setting x to 8 or higher will lead to an empty result set. (optional)
     * @param contact Return only relays with the parameter value matching (part of) the contact line. If the parameter value contains spaces, only relays are returned which contain all space-separated parts in their contact line. Only printable ASCII characters are permitted in the parameter value, some of which need to be percent-encoded (# as %23, % as %25, &amp; as %26, + as %2B, and / as %2F). Comparisons are case-insensitive. (optional)
     * @param family Return only the relay whose fingerprint matches the parameter value and all relays that this relay has listed in its family by fingerprint and that in turn have listed this relay in their family by fingerprint. If relays have listed other relays in their family by nickname, those family relationships will not be considered, regardless of whether they have the Named flag or not. The provided relay fingerprint must consist of 40 hex characters where case does not matter, and it must not be hashed using SHA-1. Bridges are not contained in the result, regardless of whether they define a family. (optional)
     * @param version Return only the relay whose fingerprint matches the parameter value and all relays that this relay has listed in its family by fingerprint and that in turn have listed this relay in their family by fingerprint. If relays have listed other relays in their family by nickname, those family relationships will not be considered, regardless of whether they have the Named flag or not. The provided relay fingerprint must consist of 40 hex characters where case does not matter, and it must not be hashed using SHA-1. Bridges are not contained in the result, regardless of whether they define a family. (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getSummaryCall(String type, String running, String search, String lookup, String fingerprint, String country, String as, String flag, BigDecimal firstSeenDays, BigDecimal lastSeenDays, String contact, String family, String version, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/summary";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (type != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "type", type));
        if (running != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "running", running));
        if (search != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "search", search));
        if (lookup != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "lookup", lookup));
        if (fingerprint != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "fingerprint", fingerprint));
        if (country != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "country", country));
        if (as != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "as", as));
        if (flag != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "flag", flag));
        if (firstSeenDays != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "first_seen_days", firstSeenDays));
        if (lastSeenDays != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "last_seen_days", lastSeenDays));
        if (contact != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "contact", contact));
        if (family != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "family", family));
        if (version != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "version", version));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getSummaryValidateBeforeCall(String type, String running, String search, String lookup, String fingerprint, String country, String as, String flag, BigDecimal firstSeenDays, BigDecimal lastSeenDays, String contact, String family, String version, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        com.squareup.okhttp.Call call = getSummaryCall(type, running, search, lookup, fingerprint, country, as, flag, firstSeenDays, lastSeenDays, contact, family, version, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Fetch a summary document
     * 
     * @param type Return only relay (parameter value relay) or only bridge documents (parameter value bridge). Parameter values are case-insensitive. (optional)
     * @param running Return only running (parameter value true) or only non-running relays and/or bridges (parameter value false). Parameter values are case-insensitive. (optional)
     * @param search Return only (1) relays with the parameter value matching (part of a) nickname, (possibly $-prefixed) beginning of a hex-encoded fingerprint, any 4 hex character block of a space-separated fingerprint, beginning of a base64-encoded fingerprint without trailing equal signs, or beginning of an IP address (possibly enclosed in square brackets in case of IPv6), (2) bridges with (part of a) nickname or (possibly $-prefixed) beginning of a hashed hex-encoded fingerprint, and (3) relays and/or bridges matching a given qualified search term. Searches by relay IP address include all known addresses used for onion routing and for exiting to the Internet. Searches for beginnings of IP addresses are performed on textual representations of canonical IP address forms, so that searches using CIDR notation or non-canonical forms will return empty results. Searches are case-insensitive, except for base64-encoded fingerprints. If multiple search terms are given, separated by spaces, the intersection of all relays and bridges matching all search terms will be returned. Complete hex-encoded fingerprints should always be hashed using SHA-1, regardless of searching for a relay or a bridge, in order to not accidentally leak non-hashed bridge fingerprints in the URL. Qualified search terms have the form \&quot;key:value\&quot; (without double quotes) with \&quot;key\&quot; being one of the parameters listed here except for \&quot;search\&quot;, \&quot;fingerprint\&quot;, \&quot;order\&quot;, \&quot;limit\&quot;, \&quot;offset\&quot;, and \&quot;fields\&quot;, and \&quot;value\&quot; being the string that will internally be passed to that parameter. If a qualified search term for a given \&quot;key\&quot; is specified more than once, only the first \&quot;value\&quot; is considered. (optional)
     * @param lookup Return only the relay with the parameter value matching the fingerprint or the bridge with the parameter value matching the hashed fingerprint. Fingerprints should always be hashed using SHA-1, regardless of looking up a relay or a bridge, in order to not accidentally leak non-hashed bridge fingerprints in the URL. Lookups only work for full fingerprints or hashed fingerprints consisting of 40 hex characters. Lookups are case-insensitive. (optional)
     * @param fingerprint Return only the relay with the parameter value matching the fingerprint or the bridge with the parameter value matching the hashed fingerprint. Fingerprints must consist of 40 hex characters, case does not matter. This parameter is quite similar to the lookup parameter with two exceptions: (1) the provided relay fingerprint or hashed bridge fingerprint must not be hashed (again) using SHA-1; (2) the response will contain any matching relay or bridge regardless of whether they have been running in the past week. (optional)
     * @param country Return only relays which are located in the given country as identified by a two-letter country code. Filtering by country code is case-insensitive. (optional)
     * @param as Return only relays which are located in the given autonomous system (AS) as identified by the AS number (with or without preceding \&quot;AS\&quot; part). Filtering by AS number is case-insensitive. (optional)
     * @param flag Return only relays which have the given relay flag assigned by the directory authorities. Note that if the flag parameter is specified more than once, only the first parameter value will be considered. Filtering by flag is case-insensitive. (optional)
     * @param firstSeenDays Return only relays or bridges which have first been seen during the given range of days ago. A parameter value \&quot;x-y\&quot; with x &lt;&#x3D; y returns relays or bridges that have first been seen at least x and at most y days ago. Accepted short forms are \&quot;x\&quot;, \&quot;x-\&quot;, and \&quot;-y\&quot; which are interpreted as \&quot;x-x\&quot;, \&quot;x-infinity\&quot;, and \&quot;0-y\&quot;. (optional)
     * @param lastSeenDays Return only relays or bridges which have last been seen during the given range of days ago. A parameter value \&quot;x-y\&quot; with x &lt;&#x3D; y returns relays or bridges that have last been seen at least x and at most y days ago. Accepted short forms are \&quot;x\&quot;, \&quot;x-\&quot;, and \&quot;-y\&quot; which are interpreted as \&quot;x-x\&quot;, \&quot;x-infinity\&quot;, and \&quot;0-y\&quot;. Note that relays and bridges that haven&#39;t been running in the past week are not included in results, so that setting x to 8 or higher will lead to an empty result set. (optional)
     * @param contact Return only relays with the parameter value matching (part of) the contact line. If the parameter value contains spaces, only relays are returned which contain all space-separated parts in their contact line. Only printable ASCII characters are permitted in the parameter value, some of which need to be percent-encoded (# as %23, % as %25, &amp; as %26, + as %2B, and / as %2F). Comparisons are case-insensitive. (optional)
     * @param family Return only the relay whose fingerprint matches the parameter value and all relays that this relay has listed in its family by fingerprint and that in turn have listed this relay in their family by fingerprint. If relays have listed other relays in their family by nickname, those family relationships will not be considered, regardless of whether they have the Named flag or not. The provided relay fingerprint must consist of 40 hex characters where case does not matter, and it must not be hashed using SHA-1. Bridges are not contained in the result, regardless of whether they define a family. (optional)
     * @param version Return only the relay whose fingerprint matches the parameter value and all relays that this relay has listed in its family by fingerprint and that in turn have listed this relay in their family by fingerprint. If relays have listed other relays in their family by nickname, those family relationships will not be considered, regardless of whether they have the Named flag or not. The provided relay fingerprint must consist of 40 hex characters where case does not matter, and it must not be hashed using SHA-1. Bridges are not contained in the result, regardless of whether they define a family. (optional)
     * @return SummaryDocument
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public SummaryDocument getSummary(String type, String running, String search, String lookup, String fingerprint, String country, String as, String flag, BigDecimal firstSeenDays, BigDecimal lastSeenDays, String contact, String family, String version) throws ApiException {
        ApiResponse<SummaryDocument> resp = getSummaryWithHttpInfo(type, running, search, lookup, fingerprint, country, as, flag, firstSeenDays, lastSeenDays, contact, family, version);
        return resp.getData();
    }

    /**
     * Fetch a summary document
     * 
     * @param type Return only relay (parameter value relay) or only bridge documents (parameter value bridge). Parameter values are case-insensitive. (optional)
     * @param running Return only running (parameter value true) or only non-running relays and/or bridges (parameter value false). Parameter values are case-insensitive. (optional)
     * @param search Return only (1) relays with the parameter value matching (part of a) nickname, (possibly $-prefixed) beginning of a hex-encoded fingerprint, any 4 hex character block of a space-separated fingerprint, beginning of a base64-encoded fingerprint without trailing equal signs, or beginning of an IP address (possibly enclosed in square brackets in case of IPv6), (2) bridges with (part of a) nickname or (possibly $-prefixed) beginning of a hashed hex-encoded fingerprint, and (3) relays and/or bridges matching a given qualified search term. Searches by relay IP address include all known addresses used for onion routing and for exiting to the Internet. Searches for beginnings of IP addresses are performed on textual representations of canonical IP address forms, so that searches using CIDR notation or non-canonical forms will return empty results. Searches are case-insensitive, except for base64-encoded fingerprints. If multiple search terms are given, separated by spaces, the intersection of all relays and bridges matching all search terms will be returned. Complete hex-encoded fingerprints should always be hashed using SHA-1, regardless of searching for a relay or a bridge, in order to not accidentally leak non-hashed bridge fingerprints in the URL. Qualified search terms have the form \&quot;key:value\&quot; (without double quotes) with \&quot;key\&quot; being one of the parameters listed here except for \&quot;search\&quot;, \&quot;fingerprint\&quot;, \&quot;order\&quot;, \&quot;limit\&quot;, \&quot;offset\&quot;, and \&quot;fields\&quot;, and \&quot;value\&quot; being the string that will internally be passed to that parameter. If a qualified search term for a given \&quot;key\&quot; is specified more than once, only the first \&quot;value\&quot; is considered. (optional)
     * @param lookup Return only the relay with the parameter value matching the fingerprint or the bridge with the parameter value matching the hashed fingerprint. Fingerprints should always be hashed using SHA-1, regardless of looking up a relay or a bridge, in order to not accidentally leak non-hashed bridge fingerprints in the URL. Lookups only work for full fingerprints or hashed fingerprints consisting of 40 hex characters. Lookups are case-insensitive. (optional)
     * @param fingerprint Return only the relay with the parameter value matching the fingerprint or the bridge with the parameter value matching the hashed fingerprint. Fingerprints must consist of 40 hex characters, case does not matter. This parameter is quite similar to the lookup parameter with two exceptions: (1) the provided relay fingerprint or hashed bridge fingerprint must not be hashed (again) using SHA-1; (2) the response will contain any matching relay or bridge regardless of whether they have been running in the past week. (optional)
     * @param country Return only relays which are located in the given country as identified by a two-letter country code. Filtering by country code is case-insensitive. (optional)
     * @param as Return only relays which are located in the given autonomous system (AS) as identified by the AS number (with or without preceding \&quot;AS\&quot; part). Filtering by AS number is case-insensitive. (optional)
     * @param flag Return only relays which have the given relay flag assigned by the directory authorities. Note that if the flag parameter is specified more than once, only the first parameter value will be considered. Filtering by flag is case-insensitive. (optional)
     * @param firstSeenDays Return only relays or bridges which have first been seen during the given range of days ago. A parameter value \&quot;x-y\&quot; with x &lt;&#x3D; y returns relays or bridges that have first been seen at least x and at most y days ago. Accepted short forms are \&quot;x\&quot;, \&quot;x-\&quot;, and \&quot;-y\&quot; which are interpreted as \&quot;x-x\&quot;, \&quot;x-infinity\&quot;, and \&quot;0-y\&quot;. (optional)
     * @param lastSeenDays Return only relays or bridges which have last been seen during the given range of days ago. A parameter value \&quot;x-y\&quot; with x &lt;&#x3D; y returns relays or bridges that have last been seen at least x and at most y days ago. Accepted short forms are \&quot;x\&quot;, \&quot;x-\&quot;, and \&quot;-y\&quot; which are interpreted as \&quot;x-x\&quot;, \&quot;x-infinity\&quot;, and \&quot;0-y\&quot;. Note that relays and bridges that haven&#39;t been running in the past week are not included in results, so that setting x to 8 or higher will lead to an empty result set. (optional)
     * @param contact Return only relays with the parameter value matching (part of) the contact line. If the parameter value contains spaces, only relays are returned which contain all space-separated parts in their contact line. Only printable ASCII characters are permitted in the parameter value, some of which need to be percent-encoded (# as %23, % as %25, &amp; as %26, + as %2B, and / as %2F). Comparisons are case-insensitive. (optional)
     * @param family Return only the relay whose fingerprint matches the parameter value and all relays that this relay has listed in its family by fingerprint and that in turn have listed this relay in their family by fingerprint. If relays have listed other relays in their family by nickname, those family relationships will not be considered, regardless of whether they have the Named flag or not. The provided relay fingerprint must consist of 40 hex characters where case does not matter, and it must not be hashed using SHA-1. Bridges are not contained in the result, regardless of whether they define a family. (optional)
     * @param version Return only the relay whose fingerprint matches the parameter value and all relays that this relay has listed in its family by fingerprint and that in turn have listed this relay in their family by fingerprint. If relays have listed other relays in their family by nickname, those family relationships will not be considered, regardless of whether they have the Named flag or not. The provided relay fingerprint must consist of 40 hex characters where case does not matter, and it must not be hashed using SHA-1. Bridges are not contained in the result, regardless of whether they define a family. (optional)
     * @return ApiResponse&lt;SummaryDocument&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<SummaryDocument> getSummaryWithHttpInfo(String type, String running, String search, String lookup, String fingerprint, String country, String as, String flag, BigDecimal firstSeenDays, BigDecimal lastSeenDays, String contact, String family, String version) throws ApiException {
        com.squareup.okhttp.Call call = getSummaryValidateBeforeCall(type, running, search, lookup, fingerprint, country, as, flag, firstSeenDays, lastSeenDays, contact, family, version, null, null);
        Type localVarReturnType = new TypeToken<SummaryDocument>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Fetch a summary document (asynchronously)
     * 
     * @param type Return only relay (parameter value relay) or only bridge documents (parameter value bridge). Parameter values are case-insensitive. (optional)
     * @param running Return only running (parameter value true) or only non-running relays and/or bridges (parameter value false). Parameter values are case-insensitive. (optional)
     * @param search Return only (1) relays with the parameter value matching (part of a) nickname, (possibly $-prefixed) beginning of a hex-encoded fingerprint, any 4 hex character block of a space-separated fingerprint, beginning of a base64-encoded fingerprint without trailing equal signs, or beginning of an IP address (possibly enclosed in square brackets in case of IPv6), (2) bridges with (part of a) nickname or (possibly $-prefixed) beginning of a hashed hex-encoded fingerprint, and (3) relays and/or bridges matching a given qualified search term. Searches by relay IP address include all known addresses used for onion routing and for exiting to the Internet. Searches for beginnings of IP addresses are performed on textual representations of canonical IP address forms, so that searches using CIDR notation or non-canonical forms will return empty results. Searches are case-insensitive, except for base64-encoded fingerprints. If multiple search terms are given, separated by spaces, the intersection of all relays and bridges matching all search terms will be returned. Complete hex-encoded fingerprints should always be hashed using SHA-1, regardless of searching for a relay or a bridge, in order to not accidentally leak non-hashed bridge fingerprints in the URL. Qualified search terms have the form \&quot;key:value\&quot; (without double quotes) with \&quot;key\&quot; being one of the parameters listed here except for \&quot;search\&quot;, \&quot;fingerprint\&quot;, \&quot;order\&quot;, \&quot;limit\&quot;, \&quot;offset\&quot;, and \&quot;fields\&quot;, and \&quot;value\&quot; being the string that will internally be passed to that parameter. If a qualified search term for a given \&quot;key\&quot; is specified more than once, only the first \&quot;value\&quot; is considered. (optional)
     * @param lookup Return only the relay with the parameter value matching the fingerprint or the bridge with the parameter value matching the hashed fingerprint. Fingerprints should always be hashed using SHA-1, regardless of looking up a relay or a bridge, in order to not accidentally leak non-hashed bridge fingerprints in the URL. Lookups only work for full fingerprints or hashed fingerprints consisting of 40 hex characters. Lookups are case-insensitive. (optional)
     * @param fingerprint Return only the relay with the parameter value matching the fingerprint or the bridge with the parameter value matching the hashed fingerprint. Fingerprints must consist of 40 hex characters, case does not matter. This parameter is quite similar to the lookup parameter with two exceptions: (1) the provided relay fingerprint or hashed bridge fingerprint must not be hashed (again) using SHA-1; (2) the response will contain any matching relay or bridge regardless of whether they have been running in the past week. (optional)
     * @param country Return only relays which are located in the given country as identified by a two-letter country code. Filtering by country code is case-insensitive. (optional)
     * @param as Return only relays which are located in the given autonomous system (AS) as identified by the AS number (with or without preceding \&quot;AS\&quot; part). Filtering by AS number is case-insensitive. (optional)
     * @param flag Return only relays which have the given relay flag assigned by the directory authorities. Note that if the flag parameter is specified more than once, only the first parameter value will be considered. Filtering by flag is case-insensitive. (optional)
     * @param firstSeenDays Return only relays or bridges which have first been seen during the given range of days ago. A parameter value \&quot;x-y\&quot; with x &lt;&#x3D; y returns relays or bridges that have first been seen at least x and at most y days ago. Accepted short forms are \&quot;x\&quot;, \&quot;x-\&quot;, and \&quot;-y\&quot; which are interpreted as \&quot;x-x\&quot;, \&quot;x-infinity\&quot;, and \&quot;0-y\&quot;. (optional)
     * @param lastSeenDays Return only relays or bridges which have last been seen during the given range of days ago. A parameter value \&quot;x-y\&quot; with x &lt;&#x3D; y returns relays or bridges that have last been seen at least x and at most y days ago. Accepted short forms are \&quot;x\&quot;, \&quot;x-\&quot;, and \&quot;-y\&quot; which are interpreted as \&quot;x-x\&quot;, \&quot;x-infinity\&quot;, and \&quot;0-y\&quot;. Note that relays and bridges that haven&#39;t been running in the past week are not included in results, so that setting x to 8 or higher will lead to an empty result set. (optional)
     * @param contact Return only relays with the parameter value matching (part of) the contact line. If the parameter value contains spaces, only relays are returned which contain all space-separated parts in their contact line. Only printable ASCII characters are permitted in the parameter value, some of which need to be percent-encoded (# as %23, % as %25, &amp; as %26, + as %2B, and / as %2F). Comparisons are case-insensitive. (optional)
     * @param family Return only the relay whose fingerprint matches the parameter value and all relays that this relay has listed in its family by fingerprint and that in turn have listed this relay in their family by fingerprint. If relays have listed other relays in their family by nickname, those family relationships will not be considered, regardless of whether they have the Named flag or not. The provided relay fingerprint must consist of 40 hex characters where case does not matter, and it must not be hashed using SHA-1. Bridges are not contained in the result, regardless of whether they define a family. (optional)
     * @param version Return only the relay whose fingerprint matches the parameter value and all relays that this relay has listed in its family by fingerprint and that in turn have listed this relay in their family by fingerprint. If relays have listed other relays in their family by nickname, those family relationships will not be considered, regardless of whether they have the Named flag or not. The provided relay fingerprint must consist of 40 hex characters where case does not matter, and it must not be hashed using SHA-1. Bridges are not contained in the result, regardless of whether they define a family. (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getSummaryAsync(String type, String running, String search, String lookup, String fingerprint, String country, String as, String flag, BigDecimal firstSeenDays, BigDecimal lastSeenDays, String contact, String family, String version, final ApiCallback<SummaryDocument> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getSummaryValidateBeforeCall(type, running, search, lookup, fingerprint, country, as, flag, firstSeenDays, lastSeenDays, contact, family, version, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<SummaryDocument>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
