/*
 * Onionoo
 * Onionoo
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package me.learmonth.iain.onionoo;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * RelaySummaryObject
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-17T21:49:33.054+01:00")
public class RelaySummaryObject {
  @SerializedName("f")
  private String f = null;

  @SerializedName("a")
  private List<String> a = new ArrayList<String>();

  @SerializedName("r")
  private Boolean r = null;

  @SerializedName("n")
  private String n = null;

  public RelaySummaryObject f(String f) {
    this.f = f;
    return this;
  }

   /**
   * Get f
   * @return f
  **/
  @ApiModelProperty(required = true, value = "")
  public String getF() {
    return f;
  }

  public void setF(String f) {
    this.f = f;
  }

  public RelaySummaryObject a(List<String> a) {
    this.a = a;
    return this;
  }

  public RelaySummaryObject addAItem(String aItem) {
    this.a.add(aItem);
    return this;
  }

   /**
   * Get a
   * @return a
  **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getA() {
    return a;
  }

  public void setA(List<String> a) {
    this.a = a;
  }

  public RelaySummaryObject r(Boolean r) {
    this.r = r;
    return this;
  }

   /**
   * Get r
   * @return r
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getR() {
    return r;
  }

  public void setR(Boolean r) {
    this.r = r;
  }

  public RelaySummaryObject n(String n) {
    this.n = n;
    return this;
  }

   /**
   * Get n
   * @return n
  **/
  @ApiModelProperty(value = "")
  public String getN() {
    return n;
  }

  public void setN(String n) {
    this.n = n;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RelaySummaryObject relaySummaryObject = (RelaySummaryObject) o;
    return Objects.equals(this.f, relaySummaryObject.f) &&
        Objects.equals(this.a, relaySummaryObject.a) &&
        Objects.equals(this.r, relaySummaryObject.r) &&
        Objects.equals(this.n, relaySummaryObject.n);
  }

  @Override
  public int hashCode() {
    return Objects.hash(f, a, r, n);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RelaySummaryObject {\n");
    
    sb.append("    f: ").append(toIndentedString(f)).append("\n");
    sb.append("    a: ").append(toIndentedString(a)).append("\n");
    sb.append("    r: ").append(toIndentedString(r)).append("\n");
    sb.append("    n: ").append(toIndentedString(n)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

