/*
 * Onionoo
 * Onionoo
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package me.learmonth.iain.onionoo;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import me.learmonth.iain.onionoo.BridgeSummaryObject;
import me.learmonth.iain.onionoo.RelaySummaryObject;

/**
 * SummaryDocument
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-17T21:49:33.054+01:00")
public class SummaryDocument {
  @SerializedName("version")
  private String version = null;

  @SerializedName("next_major_version_scheduled")
  private String nextMajorVersionScheduled = null;

  @SerializedName("build_revision")
  private String buildRevision = null;

  @SerializedName("relays_published")
  private String relaysPublished = null;

  @SerializedName("relays_skipped")
  private BigDecimal relaysSkipped = null;

  @SerializedName("relays_truncated")
  private BigDecimal relaysTruncated = null;

  @SerializedName("relays")
  private List<RelaySummaryObject> relays = new ArrayList<RelaySummaryObject>();

  @SerializedName("bridges_published")
  private String bridgesPublished = null;

  @SerializedName("bridges_skipped")
  private BigDecimal bridgesSkipped = null;

  @SerializedName("bridges_truncated")
  private BigDecimal bridgesTruncated = null;

  @SerializedName("bridges")
  private List<BridgeSummaryObject> bridges = new ArrayList<BridgeSummaryObject>();

  public SummaryDocument version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Onionoo protocol version string.
   * @return version
  **/
  @ApiModelProperty(required = true, value = "Onionoo protocol version string.")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public SummaryDocument nextMajorVersionScheduled(String nextMajorVersionScheduled) {
    this.nextMajorVersionScheduled = nextMajorVersionScheduled;
    return this;
  }

   /**
   * UTC date (YYYY-MM-DD) when the next major protocol version is scheduled to be deployed. Omitted if no major protocol changes are planned.
   * @return nextMajorVersionScheduled
  **/
  @ApiModelProperty(value = "UTC date (YYYY-MM-DD) when the next major protocol version is scheduled to be deployed. Omitted if no major protocol changes are planned.")
  public String getNextMajorVersionScheduled() {
    return nextMajorVersionScheduled;
  }

  public void setNextMajorVersionScheduled(String nextMajorVersionScheduled) {
    this.nextMajorVersionScheduled = nextMajorVersionScheduled;
  }

  public SummaryDocument buildRevision(String buildRevision) {
    this.buildRevision = buildRevision;
    return this;
  }

   /**
   * Git revision of the Onionoo instance&#39;s software used to write this response, which will be omitted if unknown.
   * @return buildRevision
  **/
  @ApiModelProperty(value = "Git revision of the Onionoo instance's software used to write this response, which will be omitted if unknown.")
  public String getBuildRevision() {
    return buildRevision;
  }

  public void setBuildRevision(String buildRevision) {
    this.buildRevision = buildRevision;
  }

  public SummaryDocument relaysPublished(String relaysPublished) {
    this.relaysPublished = relaysPublished;
    return this;
  }

   /**
   * UTC timestamp (YYYY-MM-DD hh:mm:ss) when the last known relay network status consensus started being valid. Indicates how recent the relay objects in this document are.
   * @return relaysPublished
  **/
  @ApiModelProperty(required = true, value = "UTC timestamp (YYYY-MM-DD hh:mm:ss) when the last known relay network status consensus started being valid. Indicates how recent the relay objects in this document are.")
  public String getRelaysPublished() {
    return relaysPublished;
  }

  public void setRelaysPublished(String relaysPublished) {
    this.relaysPublished = relaysPublished;
  }

  public SummaryDocument relaysSkipped(BigDecimal relaysSkipped) {
    this.relaysSkipped = relaysSkipped;
    return this;
  }

   /**
   * Number of skipped relays as requested by a positive \&quot;offset\&quot; parameter value. Omitted if zero.
   * @return relaysSkipped
  **/
  @ApiModelProperty(value = "Number of skipped relays as requested by a positive \"offset\" parameter value. Omitted if zero.")
  public BigDecimal getRelaysSkipped() {
    return relaysSkipped;
  }

  public void setRelaysSkipped(BigDecimal relaysSkipped) {
    this.relaysSkipped = relaysSkipped;
  }

  public SummaryDocument relaysTruncated(BigDecimal relaysTruncated) {
    this.relaysTruncated = relaysTruncated;
    return this;
  }

   /**
   * Number of truncated relays as requested by a positive \&quot;limit\&quot; parameter value. Omitted if zero.
   * @return relaysTruncated
  **/
  @ApiModelProperty(value = "Number of truncated relays as requested by a positive \"limit\" parameter value. Omitted if zero.")
  public BigDecimal getRelaysTruncated() {
    return relaysTruncated;
  }

  public void setRelaysTruncated(BigDecimal relaysTruncated) {
    this.relaysTruncated = relaysTruncated;
  }

  public SummaryDocument relays(List<RelaySummaryObject> relays) {
    this.relays = relays;
    return this;
  }

  public SummaryDocument addRelaysItem(RelaySummaryObject relaysItem) {
    this.relays.add(relaysItem);
    return this;
  }

   /**
   * Get relays
   * @return relays
  **/
  @ApiModelProperty(required = true, value = "")
  public List<RelaySummaryObject> getRelays() {
    return relays;
  }

  public void setRelays(List<RelaySummaryObject> relays) {
    this.relays = relays;
  }

  public SummaryDocument bridgesPublished(String bridgesPublished) {
    this.bridgesPublished = bridgesPublished;
    return this;
  }

   /**
   * UTC timestamp (YYYY-MM-DD hh:mm:ss) when the last known bridge network status consensus started being valid. Indicates how recent the relay objects in this document are.
   * @return bridgesPublished
  **/
  @ApiModelProperty(required = true, value = "UTC timestamp (YYYY-MM-DD hh:mm:ss) when the last known bridge network status consensus started being valid. Indicates how recent the relay objects in this document are.")
  public String getBridgesPublished() {
    return bridgesPublished;
  }

  public void setBridgesPublished(String bridgesPublished) {
    this.bridgesPublished = bridgesPublished;
  }

  public SummaryDocument bridgesSkipped(BigDecimal bridgesSkipped) {
    this.bridgesSkipped = bridgesSkipped;
    return this;
  }

   /**
   * Number of skipped bridges as requested by a positive \&quot;offset\&quot; parameter value. Omitted if zero.
   * @return bridgesSkipped
  **/
  @ApiModelProperty(value = "Number of skipped bridges as requested by a positive \"offset\" parameter value. Omitted if zero.")
  public BigDecimal getBridgesSkipped() {
    return bridgesSkipped;
  }

  public void setBridgesSkipped(BigDecimal bridgesSkipped) {
    this.bridgesSkipped = bridgesSkipped;
  }

  public SummaryDocument bridgesTruncated(BigDecimal bridgesTruncated) {
    this.bridgesTruncated = bridgesTruncated;
    return this;
  }

   /**
   * Number of truncated bridges as requested by a positive \&quot;limit\&quot; parameter value. Omitted if zero.
   * @return bridgesTruncated
  **/
  @ApiModelProperty(value = "Number of truncated bridges as requested by a positive \"limit\" parameter value. Omitted if zero.")
  public BigDecimal getBridgesTruncated() {
    return bridgesTruncated;
  }

  public void setBridgesTruncated(BigDecimal bridgesTruncated) {
    this.bridgesTruncated = bridgesTruncated;
  }

  public SummaryDocument bridges(List<BridgeSummaryObject> bridges) {
    this.bridges = bridges;
    return this;
  }

  public SummaryDocument addBridgesItem(BridgeSummaryObject bridgesItem) {
    this.bridges.add(bridgesItem);
    return this;
  }

   /**
   * Get bridges
   * @return bridges
  **/
  @ApiModelProperty(required = true, value = "")
  public List<BridgeSummaryObject> getBridges() {
    return bridges;
  }

  public void setBridges(List<BridgeSummaryObject> bridges) {
    this.bridges = bridges;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SummaryDocument summaryDocument = (SummaryDocument) o;
    return Objects.equals(this.version, summaryDocument.version) &&
        Objects.equals(this.nextMajorVersionScheduled, summaryDocument.nextMajorVersionScheduled) &&
        Objects.equals(this.buildRevision, summaryDocument.buildRevision) &&
        Objects.equals(this.relaysPublished, summaryDocument.relaysPublished) &&
        Objects.equals(this.relaysSkipped, summaryDocument.relaysSkipped) &&
        Objects.equals(this.relaysTruncated, summaryDocument.relaysTruncated) &&
        Objects.equals(this.relays, summaryDocument.relays) &&
        Objects.equals(this.bridgesPublished, summaryDocument.bridgesPublished) &&
        Objects.equals(this.bridgesSkipped, summaryDocument.bridgesSkipped) &&
        Objects.equals(this.bridgesTruncated, summaryDocument.bridgesTruncated) &&
        Objects.equals(this.bridges, summaryDocument.bridges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, nextMajorVersionScheduled, buildRevision, relaysPublished, relaysSkipped, relaysTruncated, relays, bridgesPublished, bridgesSkipped, bridgesTruncated, bridges);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SummaryDocument {\n");
    
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    nextMajorVersionScheduled: ").append(toIndentedString(nextMajorVersionScheduled)).append("\n");
    sb.append("    buildRevision: ").append(toIndentedString(buildRevision)).append("\n");
    sb.append("    relaysPublished: ").append(toIndentedString(relaysPublished)).append("\n");
    sb.append("    relaysSkipped: ").append(toIndentedString(relaysSkipped)).append("\n");
    sb.append("    relaysTruncated: ").append(toIndentedString(relaysTruncated)).append("\n");
    sb.append("    relays: ").append(toIndentedString(relays)).append("\n");
    sb.append("    bridgesPublished: ").append(toIndentedString(bridgesPublished)).append("\n");
    sb.append("    bridgesSkipped: ").append(toIndentedString(bridgesSkipped)).append("\n");
    sb.append("    bridgesTruncated: ").append(toIndentedString(bridgesTruncated)).append("\n");
    sb.append("    bridges: ").append(toIndentedString(bridges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

