/*
 * Onionoo
 * Onionoo
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package me.learmonth.iain.onionoo.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
